CREATE DATABASE PROJETO_PATRIMONIO

USE PROJETO_PATRIMONIO

CREATE TABLE MARCA(

MARCAID INT IDENTITY(1,1)NOT NULL,
NOME VARCHAR(100) NOT NULL,
CONSTRAINT PK_MARCA_MARCAID PRIMARY KEY(MARCAID)

)

CREATE TABLE  PATRIMONIO(

PATRIMONIOID INT IDENTITY(1,1) NOT NULL,
MARCAID INT NOT NULL,
NOME VARCHAR(100) NOT NULL,
DESCRICAO VARCHAR(150),
NUMEROTOMBO INT
CONSTRAINT  PK_PATRIMONIOID PRIMARY KEY(PATRIMONIOID)
CONSTRAINT FK_PATRIMONIO_CLIENTE_MARCAID FOREIGN KEY(MARCAID) REFERENCES MARCA(MARCAID)
)
